version: "3.7"

services:

  dev-db:
    container_name: cert-db
    image: postgres:14.2
    restart: always
    environment:
      - POSTGRES_USER=qwerty007
      - POSTGRES_PASSWORD=qwerty007
      - POSTGRES_DB=devDB
    command: ["--autovacuum=off"]
    ports:
      - "127.0.0.6:5434:5432"
    networks:
      - app-network

  dev-redis:
    container_name: redis-service
    image: redis:7.0-rc-alpine
    volumes:
      - ./storage/redis/data:/data
    restart: always
    ports:
      - 6379:6379
    networks:
      - app-network

  dev-elastic:
    container_name: elastic-service
    image: elasticsearch:7.17.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - app-network

  dev-kibana:
    container_name: kibana-service
    image: kibana:8.1.2
    links:
      - dev-elastic
    depends_on:
      - dev-elastic
    ports:
      - 5601:5601
    networks:
      - app-network

networks:
  app-network:
    driver: bridge