debug: true
server:
  servlet:
    session:
      cookie:
        same-site: lax
        http-only: false
        max-age: 360000
  logging:
    stacktrace:
      enabled: ${LOGGING_STACKTRACE:true}
      deep: 5
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:127.0.0.6}:${DB_PORT:5434}/${DB_DATABASE:devDB}?ApplicationName=cert-projects&sslmode=${DB_SSL_MODE:disable}&prepareThreshold=0
    username: ${DB_USERNAME:qwerty007}
    password: ${DB_PASSWORD:qwerty007}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: lst0n3her0@gmail.com
    password: serve123obey@
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true

  redis:
    host: localhost
    port: 6379
    password: redis

#logging:
#  level:
#    org:
#      hibernate:
#        type: trace